export const encouragementData = [
    {
        ID: 0,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'John 1:12 I am God\'s child.',
    },
    {
        ID: 1,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'John 15:15 As a disciple, I am a friend of Jesus Christ.',
    },
    {
        ID: 2,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Romans 5:1 I have been justified (declared righteous).',
    },
    {
        ID: 3,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: '1 Corinthians 6:17 I am united with the Lord, and I am one with Him in spirit.',
    },
    {
        ID: 4,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: '1 Corinthians 6:19-20 I have been bought with a price and I belong to God.',
    },
    {
        ID: 5,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: '1 Corinthians 12:27 I am a member of Christ\'s body.',
    },
    {
        ID: 6,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Ephesians 1:3-8 I have been chosen by God and adopted as His child.',
    },
    {
        ID: 7,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Colossians 1:13-14 I have been redeemed and forgiven of all my sins.',
    },
    {
        ID: 8,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Colossians 2:9-10 I am complete in Christ.',
    },
    {
        ID: 9,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'AcceptedInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Hebrews 4:14-16 I have direct access to the throne of grace through Jesus Christ.',
    },
    {
        ID: 10,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'John 15:5 I am a branch of Jesus Christ, the true vine, and a channel of His life.',
    },
    {
        ID: 11,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'John 15:16 I have been chosen and appointed to bear fruit.',
    },
    {
        ID: 12,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: '1 Corinthians 3:16 I am God\'s temple.',
    },
    {
        ID: 13,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: '2 Corinthians 5:17-21 I am a minister of reconciliation for God.',
    },
    {
        ID: 14,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Ephesians 2:6 I am seated with Jesus Christ in the heavenly realm.',
    },
    {
        ID: 15,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Ephesians 2:10 I am God\'s workmanship.',
    },
    {
        ID: 16,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Ephesians 3:12 I may approach God with freedom and confidence.',
    },
    {
        ID: 17,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SignificantInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Philippians 4:13 I can do all things through Christ, who strengthens me.',
    },
    {
        ID: 18,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Romans 8:1-2 I am free from condemnation.',
    },
    {
        ID: 19,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Romans 8:28 I am assured that God works for my good in all circumstances.',
    },
    {
        ID: 20,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Romans 8:31-39 I am free from any condemnation brought against me and I cannot be separated from the love of God.',
    },
    {
        ID: 21,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: '2 Corinthians 1:21-22 I have been established, anointed and sealed by God.',
    },
    {
        ID: 22,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Colossians 3:1-4 I am hidden with Christ in God.',
    },
    {
        ID: 23,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Philippians 1:6 I am confident that God will complete the good work He started in me.',
    },
    {
        ID: 24,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Philippians 3:20 I am a citizen of heaven.',
    },
    {
        ID: 25,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: '2 Timothy 1:7 I have not been given a spirit of fear but of power, love and a sound mind.',
    },
    {
        ID: 26,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'SecureInChrist',
        TONE: 'Uplifting',
        MESSAGE: '1 John 5:18 I am born of God and the evil one cannot touch me.',
    },
    {
        ID: 27,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'NoAnxietyInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Don’t be anxious about anything: Philippians 4:6-7 "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus" (NIV).',
    },
    {
        ID: 28,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'NoAnxietyInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'Give God your worry: 1 Peter 5:6-7 " Humble yourselves, therefore, under God’s mighty hand, that he may lift you up in due time. Cast all your anxiety on him because he cares for you " (NIV).',
    },
    {
        ID: 29,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'NoAnxietyInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'He will sustain you in the storm: Psalm 55:22 " Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken" (NIV).',
    },
    {
        ID: 30,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'NoAnxietyInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'We can trust God completely: Proverbs 3:5-6"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight " (NIV).',
    },
    {
        ID: 31,
        CATEGORY: 'WhoIAmInChrist',
        TOPIC: 'NoAnxietyInChrist',
        TONE: 'Uplifting',
        MESSAGE: 'God is bigger than our fearful hearts: Isaiah 35:4  "Say to those with fearful hearts, \'Be strong, do not fear; your God will come, he will come with vengeance; with divine retribution he will come to save you\' " (NIV).',
    },
];

